### PR TITLE
fix: Misleading HTTP status code for oauth2_client_credentials authenticator

### LINKED ISSUE #496: Misleading HTTP status code for oauth2_client_credentials authenticator
**Describe the bug**

When we are using the oauth2_client_credentials authenticator, if the token url is incorrect (upstream returns 404 HTTP status code) or upstream service is unavailable (503 Service Unavailable) Oathkeeper returns 401 Unauthorized. 

This 401 Unauthorized error message is misleading as the provided client credentials are correct.

**Reproducing the bug**

**Setup ORY Oathkeeper**

1. Create a dockerfile
```
FROM oryd/oathkeeper:v0.38.3-beta.1

ADD config.yaml /config.yaml
ADD rules.json /rules.json
ADD jwks.json /jwks.json

```
2. Build docker an image

```
$ docker build -t ory-oathkeeper-demo .
```

3. Run Oathkeeper locally
```
$ docker run --rm \
  --name ory-oathkeeper-demo \
  -p 4455:4455 \
  -p 4456:4456 \
  ory-oathkeeper-demo \
  --config /config.yaml \
  serve
```

We could refer this to [guide](https://www.ory.sh/oathkeeper/docs/configure-deploy) too.

**Setup ORY Hydra**

1. Follow the [5 minutes tutorial](https://www.ory.sh/hydra/docs/5min-tutorial) to setup Hydra.

**Make a curl request**

Request:
```
curl -X GET -H 'Authorization: Basic <your valid OAuth2 client credential>' http://127.0.0.1:4455/anything/header
```
Response:
```
{"error":{"code":401,"status":"Unauthorized","message":"oauth2: cannot fetch token: 404 Not Found\nResponse: {\"error\": \"Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port.\"}: Access credentials are invalid"}}
```

_Server logs_

```
time=2020-08-07T16:52:55Z level=warning msg=Access request denied audience=application error=map[debug: message:oauth2: cannot fetch token: 404 Not Found
Response: {"error": "Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port."}: Access credentials are invalid reason: status:Unauthorized status_code:401] granted=false http_host=127.0.0.1:4455 http_method=GET http_url=http://127.0.0.1:4455/anything/header http_user_agent=curl/7.54.0 service_name=ORY Oathkeeper service_version=v0.38.3-beta.1
time=2020-08-07T16:52:55Z level=error msg=An error occurred while handling a request code=401 debug= details=map[] error=oauth2: cannot fetch token: 404 Not Found
Response: {"error": "Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port."}: Access credentials are invalid reason= request-id= status=401 writer=JSON
time=2020-08-07T16:52:55Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* authorization:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:curl/7.54.0] host:127.0.0.1:4455 method:GET path:/anything/header query:<nil> remote:172.17.0.1:50588 scheme:http] http_response=map[status:401 text_status:Unauthorized took:5.9496ms]
```
_Server configuration_

config.yml
```
serve:
  proxy:
    port: 4455 # run the proxy at port 4455
  api:
    port: 4456 # run the api at port 4456

access_rules:
  repositories:
    - file:///rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
        # You could add some other headers, for example with data from the
        # session.
        # X-Some-Arbitrary-Data: "{{ print .Extra.some.arbitrary.data }}"
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://localhost:4455/
      jwks_url: file:///jwks.json

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  oauth2_client_credentials:
    enabled: true
    config:
      token_url: http://<your running hydra docker container ip>/oauth2/doesnotexists
```

rules.json
```
[
  {
    "id": "allow-anonymous-with-header-mutator",
    "version": "v0.36.0-beta.4",
    "upstream": {
      "url": "https://httpbin.org/anything/header"
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/anything/header",
      "methods": [
        "GET"
      ]
    },
    "authenticators": [
      {
        "handler": "oauth2_client_credentials"
      }
    ],
    "authorizer": {
      "handler": "allow"
    },
    "mutators": [
      {
        "handler": "header",
        "config": {
          "headers": {
            "X-User": "{{ print .Subject }}"
          }
        }
      }
    ]
  }
]
```

**Expected behavior**

I expect the error returned to not be 401, as the client credentials are valid. I'm not sure about the exact HTTP status code it should return, I will want to discuss more about it here.

**Environment**

Oathkeeper docker : ORY Oathkeeper service_version=v0.38.3-beta.1
OS: macOS Mojave
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### PR DESCRIPTION
**Pull request by NavindrenBaskaran**
## Related issue

[Closes #496](https://github.com/ory/oathkeeper/issues/496)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

### CODE REVIEW

**Comment by NavindrenBaskaran** [comment]
@aeneasr I've managed to return proper HTTP Error response based on the oauth2 clientcredentials response. I'm in the midst of writing test for this fix, will want to get some feedback from you.

File: pipeline/authn/authenticator_oauth2_client_credentials.go [hunk 1]
```diff
@@ -123,8 +123,23 @@ func (a *AuthenticatorOAuth2ClientCredentials) Authenticate(r *http.Request, ses
...
+				return errors.Wrapf(helper.ErrUpstreamServiceNotAvailable, err.Error())
+			} else if rErr.Response.StatusCode == http.StatusInternalServerError {
+				return errors.Wrapf(helper.ErrUpstreamServiceInternalServerError, err.Error())
+			} else if rErr.Response.StatusCode == http.StatusGatewayTimeout {
+				return errors.Wrapf(helper.ErrUpstreamServiceTimeout, err.Error())
+			} else if rErr.Response.StatusCode == http.StatusNotFound {
+				return errors.Wrapf(helper.ErrUpstreamServiceNotFound, err.Error())
+			} else if rErr.Response.StatusCode == http.StatusUnauthorized {
+				return errors.Wrapf(helper.ErrUnauthorized, err.Error())
+			}
```
Comment (aeneasr) [inline pipeline/authn/authenticator_oauth2_client_credentials.go:139]: A default case is missing. If that case were to happen, this would let the request pass even if an error occurred. I recommend using switch with a defaults!

Comment (aeneasr) [inline pipeline/authn/authenticator_oauth2_client_credentials.go:139]: A default case is missing. If that case were to happen, this would let the request pass even if an error occurred. I recommend using switch with a defaults!

**Review by aeneasr — CHANGES_REQUESTED** [review]

File: pipeline/authn/authenticator_oauth2_client_credentials.go (hunk 1 above)
Comment (NavindrenBaskaran) [reply pipeline/authn/authenticator_oauth2_client_credentials.go:140]: Hey @aeneasr, yeap have have made unauthorized as the default case.

**Comment by NavindrenBaskaran** [comment]
Hey @aeneasr can help review this please. Thanks.

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
Sorry for the slow response, this looks good! Thank you :)
